/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_heigvd_jpal_JPal */

#ifndef _Included_ch_heigvd_jpal_JPal
#define _Included_ch_heigvd_jpal_JPal
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_heigvd_jpal_JPal_P_POINT
#define ch_heigvd_jpal_JPal_P_POINT 0L
#undef ch_heigvd_jpal_JPal_P_LINE
#define ch_heigvd_jpal_JPal_P_LINE 1L
#undef ch_heigvd_jpal_JPal_P_HORIZ
#define ch_heigvd_jpal_JPal_P_HORIZ 2L
#undef ch_heigvd_jpal_JPal_P_FREE
#define ch_heigvd_jpal_JPal_P_FREE 3L
#undef ch_heigvd_jpal_JPal_P_LINE_AROUND
#define ch_heigvd_jpal_JPal_P_LINE_AROUND 4L



#undef ch_heigvd_jpal_JPal_CHAIN
#define ch_heigvd_jpal_JPal_CHAIN 0L
#undef ch_heigvd_jpal_JPal_POPMUSIC_TABU_CHAIN
#define ch_heigvd_jpal_JPal_POPMUSIC_TABU_CHAIN 1L
#undef ch_heigvd_jpal_JPal_POPMUSIC_TABU
#define ch_heigvd_jpal_JPal_POPMUSIC_TABU 2L
#undef ch_heigvd_jpal_JPal_POPMUSIC_CHAIN
#define ch_heigvd_jpal_JPal_POPMUSIC_CHAIN 3L


#undef ch_heigvd_jpal_JPal_UNIT_PIXEL
#define ch_heigvd_jpal_JPal_UNIT_PIXEL 0L
#undef ch_heigvd_jpal_JPal_UNIT_METER
#define ch_heigvd_jpal_JPal_UNIT_METER 1L
    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    new_pal
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPal_new_1pal
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    addLayer
     * Signature: (Ljava/lang/String;DDIIDZZZ)Lch/heigvd/jpal/jni/JPalLayer;
     */
    JNIEXPORT jobject JNICALL Java_ch_heigvd_jpal_JPal_addLayer
    (JNIEnv *, jobject, jstring, jdouble, jdouble, jint, jint, jdouble, jboolean, jboolean, jboolean);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    removeLayer
     * Signature: (Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPal_removeLayer
    (JNIEnv *, jobject, jstring);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    getLayers
     * Signature: ()Ljava/util/LinkedList;
     */
    JNIEXPORT jobject JNICALL Java_ch_heigvd_jpal_JPal_getLayers
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    labeller
     * Signature: ([Ljava/lang/String;[DD[DZ)Ljava/util/LinkedList;
     */
    JNIEXPORT jobject JNICALL Java_ch_heigvd_jpal_JPal_labeller
    (JNIEnv *, jobject, jobjectArray, jdoubleArray, jdouble, jdoubleArray, jobjectArray, jboolean);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    labeller_all
     * Signature: (D[DZ)Ljava/util/LinkedList;
     */
    JNIEXPORT jobject JNICALL Java_ch_heigvd_jpal_JPal_labeller_1all
    (JNIEnv *, jobject, jdouble, jdoubleArray, jobjectArray, jboolean);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    setSearchMethod
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPal_setSearchMethod
    (JNIEnv *, jobject, jint);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    getSearchMethod
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_ch_heigvd_jpal_JPal_getSearchMethod
    (JNIEnv *, jobject);


    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    setDPI
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPal_setDPI
    (JNIEnv *, jobject, jint);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    setPointP
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPal_setPointP
    (JNIEnv *, jobject, jint);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    setLineP
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPal_setLineP
    (JNIEnv *, jobject, jint);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    setPolyP
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPal_setPolyP
    (JNIEnv *, jobject, jint);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    getDPI
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_ch_heigvd_jpal_JPal_getDPI
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    getPointP
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_ch_heigvd_jpal_JPal_getPointP
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    getLineP
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_ch_heigvd_jpal_JPal_getLineP
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    getPolyP
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_ch_heigvd_jpal_JPal_getPolyP
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPal
     * Method:    getLayer
     * Signature: (Ljava/lang/String;)Lch/heigvd/jpal/jni/JPalLayer;
     */
    JNIEXPORT jobject JNICALL Java_ch_heigvd_jpal_JPal_getLayer
    (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
