/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_heigvd_jpal_JPalLayer */

#ifndef _Included_ch_heigvd_jpal_JPalLayer
#define _Included_ch_heigvd_jpal_JPalLayer
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getName
     * Signature: ()Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_ch_heigvd_jpal_JPalLayer_getName
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setActive
     * Signature: (Z)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setActive
    (JNIEnv *, jobject, jboolean);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setToLabel
     * Signature: (Z)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setToLabel
    (JNIEnv *, jobject, jboolean);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setObstacle
     * Signature: (Z)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setObstacle
    (JNIEnv *, jobject, jboolean);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setMinScale
     * Signature: (D)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setMinScale
    (JNIEnv *, jobject, jdouble);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setMaxScale
     * Signature: (D)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setMaxScale
    (JNIEnv *, jobject, jdouble);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setPriority
     * Signature: (D)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setPriority
    (JNIEnv *, jobject, jdouble);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setFeatureLabelSize
     * Signature: (Ljava/lang/String;DD)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setFeatureLabelSize
    (JNIEnv *, jobject, jstring, jdouble, jdouble);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setAlign
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setAlign
    (JNIEnv *, jobject, jint);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    registerFeature
     * Signature: (Ljava/lang/String;Ljava/lang/Object;DD)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_registerFeature
    (JNIEnv *, jobject, jstring, jobject, jdouble, jdouble);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getUnit
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_ch_heigvd_jpal_JPalLayer_getLabelUnit
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setUnit
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setLabelUnit
    (JNIEnv *, jobject, jint);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    isActive
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_ch_heigvd_jpal_JPalLayer_isActive
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    isToLabel
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_ch_heigvd_jpal_JPalLayer_isToLabel
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    isObstacle
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_ch_heigvd_jpal_JPalLayer_isObstacle
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getMinScale
     * Signature: ()D
     */
    JNIEXPORT jdouble JNICALL Java_ch_heigvd_jpal_JPalLayer_getMinScale
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getMaxScale
     * Signature: ()D
     */
    JNIEXPORT jdouble JNICALL Java_ch_heigvd_jpal_JPalLayer_getMaxScale
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getPriority
     * Signature: ()D
     */
    JNIEXPORT jdouble JNICALL Java_ch_heigvd_jpal_JPalLayer_getPriority
    (JNIEnv *, jobject);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getFeatureLabelHeight
     * Signature: (Ljava/lang/String;)D
     */
    JNIEXPORT jdouble JNICALL Java_ch_heigvd_jpal_JPalLayer_getFeatureLabelHeight
    (JNIEnv *, jobject, jstring);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getFeatureLabelWidth
     * Signature: (Ljava/lang/String;)D
     */
    JNIEXPORT jdouble JNICALL Java_ch_heigvd_jpal_JPalLayer_getFeatureLabelWidth
    (JNIEnv *, jobject, jstring);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    setFeatureDistlabel
     * Signature: (I)V
     */
    JNIEXPORT void JNICALL Java_ch_heigvd_jpal_JPalLayer_setFeatureDistlabel
    (JNIEnv *, jobject, jstring, jint);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getFeatureDistlabel
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_ch_heigvd_jpal_JPalLayer_getFeatureDistlabel
    (JNIEnv *, jobject, jstring);

    /*
     * Class:     ch_heigvd_jpal_JPalLayer
     * Method:    getAlign
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_ch_heigvd_jpal_JPalLayer_getAlign
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
